baseURL: "https://duynlk.github.io/"
theme: "papermod"
title: "DuyKa's Blog"
Copyright: |
        © 2020 - 2023 DuyKa's Blog  
        →
paginate: 10
disableHugoGeneratorInject: true
markup:
    goldmark:
        renderer:
            unsafe: true
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
    main:
        - identifier: timkiem
          name: Tìm kiếm
          url: /tim-kiem
          weight: 10
        - identifier: mucluc
          name: Mục Lục
          url: /muc-luc
          weight: 20
        - identifier: dongthoigian
          name: Dòng Thời Gian
          url: /dong-thoi-gian
          weight: 30
        - identifier: tags
          name: Tags
          url: /tags
          weight: 40
params:
    ShowPostNavLinks: true
    disableSpecial1stPost: true
    defaultTheme: light
    homeInfoParams:
        Title: "Xin chào,"
        Content: |
            -- Chiếc Blog mà bạn đang xem là tổng hợp những bài thơ/nhạc do mình - Nguyễn Lữ Khánh Duy, sáng tác, phỏng dịch và chuyển ngữ kể từ năm 2020.  
            -- Mình thường lấy bút danh là **#DuyKa** khi gửi bài trên [ThiVien.net](https://www.thivien.net/translator/DuyKa), các cuộc thi & hội nhóm thơ-văn.  
            -- Cảm ơn bạn đã ghé qua đây, rất mong nhận được ý kiến đóng góp, phê bình từ bạn ^^