baseURL: "https://duynlk.github.io/"
theme: "papermod"
title: "DuyKa's Blog"
Copyright: |
        © 2020 - 2024 DuyKa's Blog  
        →
paginate: 10
disableHugoGeneratorInject: true
markup:
    goldmark:
        renderer:
            unsafe: true
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
    main:
        - identifier: timkiem
          name: Tìm kiếm
          url: /tim-kiem
          weight: 10
        - identifier: mucluc
          name: Mục Lục
          url: /muc-luc
          weight: 20
        - identifier: dongthoigian
          name: Dòng Thời Gian
          url: /dong-thoi-gian
          weight: 30
        - identifier: tags
          name: Tags
          url: /tags
          weight: 40
params:
    ShowPostNavLinks: true
    disableSpecial1stPost: false
    defaultTheme: light